version: "3.9"  # optional since v1.27.0
services:
  toolbox:
    init: false
    build: .
    env_file:
      - .env
    volumes:
      - ./tmp:/tmp
      - ./ansible:/devops/ansible
      - ./packer:/devops/packer
      - ./terraform:/devops/terraform