- name: Deploy stack config
  template:
    src: docker-compose.yml.j2
    dest: /srv/docker-compose.yml
  tags:
    - stack

- name: Run `docker-compose up -d`
  shell: docker-compose up -d
  args:
    chdir: /srv
  tags:
    - stack