---
- name: Provision docker-node
  hosts: group_docker_node
  user: ubuntu
  gather_facts: false
  roles:
    - role: docker
      become: yes
    - role: docker-compose
      become: yes
    - role: stack
      become: yes