---
- name: Provision docker-node
  hosts: group_docker_node
  user: ubuntu
  become: yes
  gather_facts: false
  roles:
    - role: docker
      become: true
    - role: docker-compose
      become: true